AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a simple inline StackSet - (v1.0.0)"
Parameters:
  # General Configuration
  InfrastructureName:
    Type: "String"
    Description: "A name used to differentiate this infrastructure from other existing infrastructure."
    Default: "main"
  AppBaseFolder:
    Type: "String"
    Description: "The base repository folder for the application."
  # StackSet Configuration
  StackSetName:
    Type: "String"
    Description: "The name of the StackSet."
    Default: "test"
  StackSetDescription:
    Type: "String"
    Description: "The description of the StackSet."
    Default: "Main inline testing StackSet."
  StackSetVersion:
    Type: "String"
    Description: "A version number for the StackSet."
  PermissionModel:
    Type: "String"
    Description: "The permissions model being used with the StackSet."
    AllowedValues:
    - "SELF_MANAGED"
    - "SERVICE_MANAGED"
    Default: "SELF_MANAGED"
Conditions:
  AppBaseFolder: !Not [ !Equals [ !Ref AppBaseFolder, "" ] ]
Resources:
  StackSet:
    Type: "AWS::CloudFormation::StackSet"
    DeletionPolicy: "Retain"
    UpdateReplacePolicy: "Retain"
    Properties:
      StackSetName: !Sub "${InfrastructureName}-${StackSetName}-inline"
      Description: !Ref StackSetDescription
      PermissionModel: !Ref PermissionModel
      ManagedExecution:
        Active: true
      Tags:
      - Key: "Name"
        Value: !Ref "AWS::StackName"
      - Key: "application"
        Value: !Ref "AWS::StackName"
      - Key: "contact-email"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/contact-email}}"
      - Key: "customer"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/customer}}"
      - Key: "environment"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/environment}}"
      - Key: "team"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/team}}"
      Parameters:
      - ParameterKey: "TopicName"
        ParameterValue: "stackset-test-topic"
      - ParameterKey: "DisplayName"
        ParameterValue: "Stackset:"
      TemplateBody: |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: "Create a new SNS Topic (in-line)"
        Parameters:
          TopicName:
            Type: "String"
            Description: "The name of the topic."
            AllowedPattern: "[a-zA-Z0-9-_]+"
          DisplayName:
            Type: "String"
            Description: "A developer-defined string that can be used to identify this SNS topic."
            MaxLength: 10
        Resources:
          Topic:
            Type: "AWS::SNS::Topic"
            Properties:
              TopicName: !Ref TopicName
              DisplayName: !Ref DisplayName
        Outputs:
          TopicArn:
            Description: "The ARN of this topic."
            Value: !Ref Topic
            Export:
              Name: !Sub "${AWS::StackName}-TopicArn"
          TopicName:
            Description: "The name of this topic."
            Value: !GetAtt Topic.TopicName
            Export:
              Name: !Sub "${AWS::StackName}-TopicName"
        Metadata:
          AWS::CloudFormation::Interface:
            ParameterGroups:
            - Label:
                default: "General Configuration"
              Parameters:
              - TopicName
              - DisplayName
            ParameterLabels:
              TopicName:
                default: "Topic Name:"
              DisplayName:
                default: "Display Name:"
      # TemplateBody: |
      #   {
      #     "AWSTemplateFormatVersion": "2010-09-09",
      #     "Resources": {
      #       "testWaitHandle": {
      #         "Type": "AWS::CloudFormation::WaitConditionHandle"
      #       }
      #     }
      #   }
Outputs:
  StackSetId:
    Description: "The StackSet ID."
    Value: !Ref StackSet
    Export:
      Name: !Sub "${AWS::StackName}-StackSetId"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - InfrastructureName
      - AppBaseFolder
    - Label:
        default: "StackSet Configuration"
      Parameters:
      - StackSetName
      - StackSetDescription
      - StackSetVersion
    ParameterLabels:
      InfrastructureName:
        default: "Infrastructure Name:"
      AppBaseFolder:
        default: "Application BasebFolder:"
      StackSetName:
        default: "StackSet Name:"
      StackSetDescription:
        default: "StackSet Description:"
      StackSetVersion:
        default: "StackSet Version:"
