AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a StackSet from a template in an S3 bucket - (v1.0.0)"
Parameters:
  # General Configuration
  InfrastructureName:
    Type: "String"
    Description: "A name used to differentiate this infrastructure from other existing infrastructure."
    Default: "main"
  AppBaseFolder:
    Type: "String"
    Description: "The base repository folder for the application."
  # StackSet Configuration
  StackSetName:
    Type: "String"
    Description: "The name of the StackSet."
    Default: "test"
  StackSetDescription:
    Type: "String"
    Description: "The description of the StackSet."
    Default: "Main S3 testing StackSet."
  StackSetVersion:
    Type: "String"
    Description: "A version number for the StackSet."
  PermissionModel:
    Type: "String"
    Description: "The permissions model being used with the StackSet."
    AllowedValues:
    - "SELF_MANAGED"
    - "SERVICE_MANAGED"
    Default: "SELF_MANAGED"
  # Default Stack Parameters
  TopicBaseName:
    Type: "String"
    Description: "The base name of the topic."
    AllowedPattern: "[a-zA-Z0-9-_]+"
    Default: "stackset-test-topic-s3"
  DisplayName:
    Type: "String"
    Description: "A developer-defined string that can be used to identify this SNS topic."
    MaxLength: 10
    Default: "DEFAULT"
  # S3 Configuration
  BucketName:
    Type: "String"
    Description: "The name of the S3 bucket."
  BucketRegion:
    Type: "String"
    Description: "The region of the S3 bucket."
  BucketPath:
    Type: "String"
    Description: "The file path for the file in the S3 bucket."
  BucketFile:
    Type: "String"
    Description: "The name of the S3 bucket."
Conditions:
  AppBaseFolder: !Not [ !Equals [ !Ref AppBaseFolder, "" ] ]
Resources:
  StackSet:
    Type: "AWS::CloudFormation::StackSet"
    DeletionPolicy: "Retain"
    UpdateReplacePolicy: "Retain"
    Properties:
      StackSetName: !Sub "${InfrastructureName}-${StackSetName}-s3"
      Description: !Ref StackSetDescription
      PermissionModel: !Ref PermissionModel
      ManagedExecution:
        Active: true
      Tags:
      - Key: "Name"
        Value: !Ref "AWS::StackName"
      - Key: "application"
        Value: !Ref "AWS::StackName"
      - Key: "contact-email"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/contact-email}}"
      - Key: "customer"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/customer}}"
      - Key: "environment"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/environment}}"
      - Key: "team"
        Value: !Sub "{{resolve:ssm:/account/${InfrastructureName}/tag/team}}"
      Parameters:
      - ParameterKey: "TopicBaseName"
        ParameterValue: !Ref TopicBaseName
      - ParameterKey: "DisplayName"
        ParameterValue: !Ref DisplayName
      TemplateURL: !Sub "https://s3.${BucketRegion}.amazonaws.com/${BucketName}/${BucketPath}/${BucketFile}"
Outputs:
  StackSetId:
    Description: "The StackSet ID."
    Value: !Ref StackSet
    Export:
      Name: !Sub "${AWS::StackName}-StackSetId"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - InfrastructureName
      - AppBaseFolder
    - Label:
        default: "Stack Parameter Configuration"
      Parameters:
      - TopicBaseName
      - DisplayName
    - Label:
        default: "StackSet Configuration"
      Parameters:
      - StackSetName
      - StackSetDescription
      - StackSetVersion
    ParameterLabels:
      InfrastructureName:
        default: "Infrastructure Name:"
      AppBaseFolder:
        default: "Application BasebFolder:"
      StackSetName:
        default: "StackSet Name:"
      StackSetDescription:
        default: "StackSet Description:"
      StackSetVersion:
        default: "StackSet Version:"
      TopicBaseName:
        default: "Topic Base Name:"
      DisplayName:
        default: "Display Name:"
